// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGdi48ir0fy-KxtbCE7sHJQZV0KOtbU6g',
    appId: '1:1028297987047:web:820410d2f0f82456b72342',
    messagingSenderId: '1028297987047',
    projectId: 'flutterfirebase-4eb78',
    authDomain: 'flutterfirebase-4eb78.firebaseapp.com',
    storageBucket: 'flutterfirebase-4eb78.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoS7yEHofQb-3-mdKGgTEH_EiMHJzXdLU',
    appId: '1:1028297987047:android:1f0af2ecf77665eeb72342',
    messagingSenderId: '1028297987047',
    projectId: 'flutterfirebase-4eb78',
    storageBucket: 'flutterfirebase-4eb78.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9wr2bb20UiJ27Vwhh4sHBnP95ti4qD-0',
    appId: '1:1028297987047:ios:70e9ef66a0a40f1cb72342',
    messagingSenderId: '1028297987047',
    projectId: 'flutterfirebase-4eb78',
    storageBucket: 'flutterfirebase-4eb78.firebasestorage.app',
    iosBundleId: 'com.example.proyectoFirebaseDap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9wr2bb20UiJ27Vwhh4sHBnP95ti4qD-0',
    appId: '1:1028297987047:ios:70e9ef66a0a40f1cb72342',
    messagingSenderId: '1028297987047',
    projectId: 'flutterfirebase-4eb78',
    storageBucket: 'flutterfirebase-4eb78.firebasestorage.app',
    iosBundleId: 'com.example.proyectoFirebaseDap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGdi48ir0fy-KxtbCE7sHJQZV0KOtbU6g',
    appId: '1:1028297987047:web:122dafed4e84b2feb72342',
    messagingSenderId: '1028297987047',
    projectId: 'flutterfirebase-4eb78',
    authDomain: 'flutterfirebase-4eb78.firebaseapp.com',
    storageBucket: 'flutterfirebase-4eb78.firebasestorage.app',
  );
}
